FROM openjdk:11.0.7-jre-slim

ARG APP_JAR
ARG GIT_COMMIT_ID
ARG JENKINS_BUILD_TAG

LABEL GIT_COMMIT_ID=${GIT_COMMIT_ID} \
      JENKINS_BUILD_TAG=${JENKINS_BUILD_TAG}

COPY ${APP_JAR} /app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]